Styling and Linters
David-Verde/Bookstore pull request #9
Opened 2022-07-14 20:57 UTC by David-Verde

Add SCSS Style
Install SASS dependencies on project
Fix linter using Eslint and Stylelint Extentions

2022-07-14 21:40 UTC, MeqdamAlqudah requested changes
Hi @David-Verde , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-14 21:40 UTC, MeqdamAlqudah commented on package.json
>      "eslint-plugin-react": "^7.30.1",
- [ ] Please there is an issue in the code 
![image](https://user-images.githubusercontent.com/74744787/179090787-b7030c34-7119-4c4c-881b-bee1cec51379.png)

2022-07-14 22:10 UTC, ShahierNashaat requested changes
Hi @David-Verde , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-14 22:10 UTC, ShahierNashaat commented on src/components/BookForm.jsx
> +
- [ ] Kindly be noticed that adding a book is not working please fix that.
- [ ] Also the `ADD BOOK` button goes over the categories select menu please fix that.

![Screenshot from 2022-07-15 00-09-29](https://user-images.githubusercontent.com/33752735/179097016-2a5e532f-dab7-4931-b70c-3f6d70c57f0f.png)

2022-07-15 14:28 UTC, David-Verde commented on src/components/BookForm.jsx
> +
ok i fix both Issues thanks for let me know.

2022-07-15 14:33 UTC, Deepakdanger approved these changes
Hi @David-Verde, 

### Status: Approved ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚢 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-12 14:36 UTC, merged